# Generated by Django 3.2.3 on 2021-05-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('Meat', 'Meat'), ('Produce', 'Produce'), ('Dairy', 'Dairy'), ('Beverages', 'Beverages'), ('Starch', 'Starch')], default='Produce', max_length=25),
        ),
    ]
