# Generated by Django 3.2.3 on 2021-05-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_app', '0002_fooditem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('Meat', 'Meat'), ('Produce', 'Produce'), ('Dairy', 'Dairy'), ('Beverages', 'Beverages'), ('Other', 'Other')], default='Other', max_length=25),
        ),
    ]
