# Generated by Django 3.2.3 on 2021-07-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_app', '0002_auto_20210629_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='continent',
            field=models.CharField(blank=True, choices=[('Asia', 'Asia'), ('Africa', 'Africa'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America'), ('Australia/Oceania', 'Australia/Oceania'), ('Antarctica', 'Antarctica')], default='Asia', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='income',
            field=models.CharField(blank=True, choices=[('0 to 10k', '0 to 10k'), ('10k to 20k', '10k to 20k'), ('20k to 40k', '20k to 40k'), ('40k to 60k', '40k to 60k'), ('60k to 80k', '60k to 80k'), ('80k to 100k', '80k to 100k'), ('Over 150k', 'Over 150k')], default='0 to 10k', max_length=25, null=True),
        ),
    ]
