# Generated by Django 3.2.3 on 2021-05-28 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco_app', '0003_alter_fooditem_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
