# Generated by Django 3.2.3 on 2021-06-04 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco_app', '0010_rename_daily_checkin_daily'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='daily',
        ),
        migrations.DeleteModel(
            name='Daily',
        ),
    ]
