# Generated by Django 3.2.3 on 2021-06-08 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eco_app', '0011_auto_20210603_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='item',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='servings',
        ),
        migrations.CreateModel(
            name='Servings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eco_app.checkin')),
            ],
        ),
    ]
