# Generated by Django 3.2.3 on 2021-06-08 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco_app', '0012_auto_20210607_2038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servings',
            new_name='Serving',
        ),
    ]
