# Generated by Django 3.2.3 on 2021-06-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_app', '0013_rename_servings_serving'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
