# Generated by Django 3.2.3 on 2021-06-11 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_app', '0017_alter_checkin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
