# Generated by Django 3.2.3 on 2021-06-16 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eco_app', '0019_alter_checkin_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipCode', models.CharField(blank=True, max_length=5)),
                ('continent', models.CharField(choices=[('Asia', 'Asia'), ('Africa', 'Africa'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America'), ('Australia/Oceania', 'Australia/Oceania'), ('Antarctica', 'Antarctica')], default='Asia', max_length=20)),
                ('income', models.IntegerField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
