# Generated by Django 3.2.3 on 2021-06-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_app', '0020_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='continent',
            field=models.CharField(blank=True, choices=[('Asia', 'Asia'), ('Africa', 'Africa'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America'), ('Australia/Oceania', 'Australia/Oceania'), ('Antarctica', 'Antarctica')], max_length=20, null=True),
        ),
    ]
