# Generated by Django 3.2.3 on 2021-06-17 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eco_app', '0021_alter_profile_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='income',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zipCode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
