# Generated by Django 3.2.3 on 2021-06-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_app', '0022_auto_20210616_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='continent',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
