# Generated by Django 3.2.3 on 2021-06-18 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eco_app', '0023_alter_profile_continent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='user',
        ),
        migrations.AddField(
            model_name='checkin',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eco_app.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zipCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
