# Generated by Django 3.2.3 on 2021-06-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_app', '0025_alter_profile_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile'),
        ),
    ]
